steps:
- name: 'gcr.io/cloudrun/pack'
  args: ['build', '--builder=heroku/buildpacks:18', '--path', 'samples/java-quarkus', '--publish', 'gcr.io/$PROJECT_ID/$REPO_NAME-samples-java-quarkus:$COMMIT_SHA']
