steps:
- name: 'gcr.io/cloudrun/pack'
  args: ['build', '--builder=heroku/buildpacks:18', '--path', 'samples/java-springboot', '--publish', 'gcr.io/$PROJECT_ID/cloudbowl-samples-java-springboot:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '--image=gcr.io/$PROJECT_ID/cloudbowl-samples-java-springboot:$COMMIT_SHA', '--platform=managed', '--project=$PROJECT_ID', '--region=us-central1', '--allow-unauthenticated', '--memory=256Mi', 'cloudbowl-samples-java-springboot']
